printing secret

diff --git a/.github/workflows/secrets-vault-action-e2e-test.yaml b/.github/workflows/secrets-vault-action-e2e-test.yaml
--- a/.github/workflows/secrets-vault-action-e2e-test.yaml
+++ b/.github/workflows/secrets-vault-action-e2e-test.yaml
@@ -14,7 +14,7 @@ jobs:
 
       - name: Fetch secret using username/password authentication
         id: fetch-secret
-        uses: EntrustCorporation/secrets-vault-action@v1
+        uses: sunithkumarp-entrust/demo-pasm-vault-action@main
         with:
           base_url: ${{ secrets.BASE_URL }}
           auth_type: 'userpass'
@@ -33,6 +33,10 @@ jobs:
 
       - name: Compare secrets with GitHub secrets
         run: |
+          echo '${{ toJson(steps.fetch-secret.outputs) }}' >> example.json
+
+          cat example.json
+
           if [[ "${{ steps.fetch-secret.outputs.AWS_ACCESS_KEY_ID }}" != "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then
             echo "AWS_ACCESS_KEY_ID does not match!"
             exit 1
@@ -53,4 +57,18 @@ jobs:
             echo "DOCKER_PASSWORD does not match!"
             exit 1
           fi
+          if [[ "${{ steps.fetch-secret.outputs.EXAMPLE_TEXT_SECRET }}" != "${{ secrets.EXAMPLE_TEXT_SECRET }}" ]]; then
+            echo "EXAMPLE_TEXT_SECRET does not match!"
+            exit 1
+          fi
+          if [[ "${{ steps.fetch-secret.outputs.SIMPLE_KV_SECRET }}" != "${{ secrets.SIMPLE_KV_SECRET }}" ]]; then
+            echo "SIMPLE_KV_SECRET does not match!"
+            exit 1
+          fi
           echo "All secrets match successfully!"
+  
+      - name: Clean up
+        if: always()  # Run even if previous steps fail
+        run: |
+          # Securely remove sensitive files - DO NOT SKIP THIS STEP
+          shred -u example.json
